[project]
name = "fastapi-echo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lestherll", email = "ljllacuna5@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.1",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
